name:  Question
description: Question Submission
title: "[Question]"
labels: ["question"]
projects: ["Policy"]
assignees: 
 - mrchrisadams
 - muemich
 - lisamcnally
body:
  - type: textarea
    id: Question
    attributes:
      label: Question
      description: Question submission for group members
      placeholder: Tell us what you see
      value: "Question submission details"
    validations:
      required: true
  - type: dropdown
    id: TF-Groups
    attributes:
      label: Issue dependency with other TF Groups
      multiple: true
      options:
        - No Dependency
        - Standards-WG
        - Community-WG
        - Opensource-WG
